title: Zixuan (Eve) Yi
logo: /img/photo.jpg
description: zixy@upenn.edu \n **PhD Student @ UPenn \n Machine Learning × Data × Systems** \n [Google Scholar](https://scholar.google.com/citations?user=yN_59vUAAAAJ&hl=en) · [GitHub](https://github.com/zixy17) · [Twitter](https://twitter.com/yi_zixuan) · [LinkedIn](https://www.linkedin.com/in/zixuan-yi-073ab01b0/) · [Email](mailto:zixy@upenn.edu)

theme: jekyll-theme-minimal
